//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Website_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONUS_TIME
    {
        public int BONUS_TIME_ID { get; set; }
        public byte START_TIME { get; set; }
        public byte END_TIME { get; set; }
    }
}
