//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Website_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOB()
        {
            this.JOB_RECUMENT = new HashSet<JOB_RECUMENT>();
        }
    
        public int JOB_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public string JOB_CODE { get; set; }
        public string JOB_NAME { get; set; }
        public Nullable<double> MINIMUM_WAGE { get; set; }
        public Nullable<double> MAXIMUM_WAGE { get; set; }
        public Nullable<int> TOWN_ID { get; set; }
        public string JOB_REQUIREMENT { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public Nullable<int> SHIFT_WORK { get; set; }
    
        public virtual JOB_CATEGORY JOB_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB_RECUMENT> JOB_RECUMENT { get; set; }
        public virtual SHIFT_WORK_SCHEDULE SHIFT_WORK_SCHEDULE { get; set; }
        public virtual TOWN TOWN { get; set; }
    }
}
