//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Website_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_RECUMENT_PROCESSING
    {
        public int RECUMENT_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string APPLYING_DATE { get; set; }
        public Nullable<bool> APPROVAL_STATUS { get; set; }
        public Nullable<int> JOB_STATUS { get; set; }
        public Nullable<int> WAGE_PAYMENT_STATUS { get; set; }
    
        public virtual JOB_RECUMENT JOB_RECUMENT { get; set; }
        public virtual PROFILE PROFILE { get; set; }
    }
}
