-- CREATE DATABASE PartTimeJob;
-- GO
USE PartTimeJob;
GO

-- Data Source : Custom / Database Name : PartTimeJob / User : sa / Password : sa .
-- Final SQL Query For Dot Net Website Project , No Error Command .
-- Update : 26/05/2019 .
-- Pham Quang Tuan .

CREATE TABLE PROVINCE(
PROVINCE_ID TINYINT IDENTITY(1,1) PRIMARY KEY,
PROVINCE_NAME NVARCHAR(25) UNIQUE
)
GO
CREATE TABLE TOWN(
TOWN_ID INT IDENTITY(1,1) PRIMARY KEY,	
PROVINCE_ID TINYINT NOT NULL,
TOWN_NAME NVARCHAR(25) UNIQUE,
CONSTRAINT FK_PV FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE(PROVINCE_ID),
CONSTRAINT VALIDATE_TOWN UNIQUE(PROVINCE_ID, TOWN_NAME)
)
GO
CREATE TABLE ROLE(
ROLE_ID TINYINT IDENTITY(1,1) PRIMARY KEY,
ROLE_NAME NVARCHAR(50)
)
GO
CREATE TABLE "USER"(
USER_ID INT IDENTITY(1,1) PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
USER_STATUS TINYINT ,
ROLE_ID TINYINT  ,
JOINED_DATE VARCHAR(10) ,
FACEBOOK_ID VARCHAR(100) UNIQUE,
GMAIL_ID VARCHAR(100) UNIQUE,
RESET_TOKEN VARCHAR(100)
CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
)
GO
CREATE TABLE PROFILE(
PROFILE_ID INT IDENTITY(1,1) PRIMARY KEY,
FIRST_NAME NVARCHAR(50),
LAST_NAME NVARCHAR(50),
IDENTITY_CARD char(12),
BIRTHDAY VARCHAR(10),
SEX VARCHAR(10),
EMAIL VARCHAR(50),
PHONE INT,
TOWN_ID INT,
ADDRESS NVARCHAR(100),
AVATAR VARCHAR(100),
DESCRIPTION NVARCHAR(255),
CONSTRAINT FK_TOWN FOREIGN KEY (TOWN_ID) REFERENCES TOWN(TOWN_ID)
)
GO
CREATE TABLE TYPEPAYCARD(
TYPEPAYCARD_ID TINYINT IDENTITY(1,1)PRIMARY KEY,
PAYCARD_NAME VARCHAR(50)
)
GO
CREATE TABLE USERPAYCARDS(
PAYCARD_NO INT IDENTITY(1,1),
CARD_NUMBER VARCHAR(20) PRIMARY KEY,
PROFILE_ID INT NOT NULL,
TYPEPAYCARD_ID TINYINT NOT NULL,
NOW_USING BIT 
CONSTRAINT VALIDATE_PAYCARD UNIQUE(CARD_NUMBER,PROFILE_ID)
CONSTRAINT FK_TYPEPAYCARD FOREIGN KEY(TYPEPAYCARD_ID) REFERENCES TYPEPAYCARD(TYPEPAYCARD_ID)
)
GO


CREATE TABLE BONUS_TIME(
BONUS_TIME_ID INT IDENTITY(1,1) PRIMARY KEY,
START_TIME TINYINT NOT NULL,
END_TIME TINYINT NOT NULL
)
GO

CREATE TABLE WORK_TIME(
WORK_TIME_ID INT IDENTITY(1,1) PRIMARY KEY,
START_TIME TINYINT NOT NULL,
END_TIME TINYINT NOT NULL,
FIRST_BONUSTIME_ID INT,
SECOND_BONUSTIME_ID INT
)
GO

CREATE TABLE SHIFT_WORK_SCHEDULE(
SHIFT_ID INT IDENTITY(1,1) PRIMARY KEY,
MON_WORK_TIME INT,
TUES_WORK_TIME INT,
WED_WORK_TIME INT,
THURS_WORK_TIME INT,
FRI_WORK_TIME INT,
SAT_WORK_TIME INT,
SUN_WORK_TIME INT,
CONSTRAINT FK_M FOREIGN KEY (MON_WORK_TIME) REFERENCES WORK_TIME(WORK_TIME_ID),
CONSTRAINT FK_T FOREIGN KEY (TUES_WORK_TIME) REFERENCES WORK_TIME(WORK_TIME_ID),
CONSTRAINT FK_W FOREIGN KEY (WED_WORK_TIME) REFERENCES WORK_TIME(WORK_TIME_ID),
CONSTRAINT FK_TH FOREIGN KEY (THURS_WORK_TIME) REFERENCES WORK_TIME(WORK_TIME_ID),
CONSTRAINT FK_F FOREIGN KEY (FRI_WORK_TIME) REFERENCES WORK_TIME(WORK_TIME_ID),
CONSTRAINT FK_S FOREIGN KEY (SAT_WORK_TIME) REFERENCES WORK_TIME(WORK_TIME_ID),
CONSTRAINT FK_SU FOREIGN KEY (SUN_WORK_TIME) REFERENCES WORK_TIME(WORK_TIME_ID)
)
GO

CREATE TABLE JOB_CATEGORY(
CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
CATEGORY_NAME NVARCHAR(50) 
)

CREATE TABLE JOB(
JOB_ID INT IDENTITY(1,1) PRIMARY KEY,
CATEGORY_ID INT NOT NULL,
JOB_CODE VARCHAR(50) NOT NULL,
JOB_NAME NVARCHAR(50) ,
MINIMUM_WAGE FLOAT,
MAXIMUM_WAGE FLOAT,
TOWN_ID INT,
JOB_REQUIREMENT NVARCHAR(255),
JOB_DESCRIPTION NVARCHAR(255),
SHIFT_WORK INT,
CONSTRAINT FK_CATE FOREIGN KEY (CATEGORY_ID) REFERENCES JOB_CATEGORY(CATEGORY_ID),
CONSTRAINT FK_TOWN2 FOREIGN KEY (TOWN_ID) REFERENCES TOWN(TOWN_ID),
CONSTRAINT FK_SHIFT1 FOREIGN KEY (SHIFT_WORK) REFERENCES SHIFT_WORK_SCHEDULE(SHIFT_ID)
)
GO

CREATE TABLE JOB_RECUMENT(
RECUMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
EMPLOYER_ID INT NOT NULL,
EMPLOYEE_AMOUNT INT ,
JOB_ID INT ,
START_DATE VARCHAR(50),
WORK_MONTH_AMOUNT INT ,
CREATED_DATE VARCHAR(50),
APPROVAL_DEADLINE VARCHAR(50),
REFERRAL_WAGE_COST FLOAT,
RECUMENT_STATUS INT DEFAULT 1,
CONSTRAINT FK_EMPLOYER FOREIGN KEY (EMPLOYER_ID) REFERENCES PROFILE(PROFILE_ID),
CONSTRAINT FK_JOB1 FOREIGN KEY (JOB_ID) REFERENCES JOB(JOB_ID)
)
GO

CREATE TABLE JOB_RECUMENT_PROCESSING(
RECUMENT_ID INT,
EMPLOYEE_ID INT,
APPLYING_DATE VARCHAR(50) NOT NULL,
APPROVAL_STATUS BIT DEFAULT 0,
JOB_STATUS INT DEFAULT 1,
WAGE_PAYMENT_STATUS INT DEFAULT 0,
PRIMARY KEY (RECUMENT_ID, EMPLOYEE_ID),
CONSTRAINT FK_RECU FOREIGN KEY (RECUMENT_ID) REFERENCES JOB_RECUMENT(RECUMENT_ID),
CONSTRAINT FK_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES PROFILE(PROFILE_ID)
)
GO

CREATE TABLE FEED_BACKLIST(
RECUMENT_ID INT,
FEEDBACK_EMPLOYER INT,
FEEDBACK_EMPLOYEE INT,
STAR_CONSIDER INT,
CONTENT NVARCHAR(255),
PRIMARY KEY (RECUMENT_ID, FEEDBACK_EMPLOYER, FEEDBACK_EMPLOYEE),
CONSTRAINT FK_RECU2 FOREIGN KEY (RECUMENT_ID) REFERENCES JOB_RECUMENT(RECUMENT_ID),
CONSTRAINT FK_EMP1 FOREIGN KEY (FEEDBACK_EMPLOYER) REFERENCES PROFILE(PROFILE_ID),
CONSTRAINT FK_EMP2 FOREIGN KEY (FEEDBACK_EMPLOYEE) REFERENCES PROFILE(PROFILE_ID)
)
GO

CREATE TABLE REFERRAL_WAGE_BILL(
REFERRAL_ID INT IDENTITY(1,1) PRIMARY KEY,
RECUMENT_ID INT NOT NULL,
REFERRAL_WAGE_COST FLOAT ,
PAYMENT_DATE VARCHAR(50),
CARD_NUMBER VARCHAR(20),
CONSTRAINT FK_RECU3 FOREIGN KEY (RECUMENT_ID) REFERENCES JOB_RECUMENT(RECUMENT_ID),
CONSTRAINT FK_CARD FOREIGN KEY (CARD_NUMBER) REFERENCES USERPAYCARDS(CARD_NUMBER)
)
GO

CREATE TABLE JOB_WAGE_BILL(
JOB_BILL_ID INT IDENTITY(1,1) PRIMARY KEY,
RECUMENT_ID INT NOT NULL,
EMPLOYER_ID INT,
EMPLOYEE_ID INT,
JOB_WAGE_COST FLOAT,
EMLOYER_CARDNUMBER VARCHAR(20),
EMPLOYEE_CARDNUMBER VARCHAR(20),
CONSTRAINT FK_RECU4 FOREIGN KEY (RECUMENT_ID) REFERENCES JOB_RECUMENT(RECUMENT_ID),
CONSTRAINT FK_EMP3 FOREIGN KEY (EMPLOYER_ID) REFERENCES PROFILE(PROFILE_ID),
CONSTRAINT FK_EMP4 FOREIGN KEY (EMPLOYEE_ID) REFERENCES PROFILE(PROFILE_ID),
CONSTRAINT FK_CARD2 FOREIGN KEY (EMLOYER_CARDNUMBER) REFERENCES USERPAYCARDS(CARD_NUMBER),
CONSTRAINT FK_CARD3 FOREIGN KEY (EMPLOYEE_CARDNUMBER) REFERENCES USERPAYCARDS(CARD_NUMBER)
)
GO
