//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Website_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEED_BACKLIST
    {
        public int RECUMENT_ID { get; set; }
        public int FEEDBACK_EMPLOYER { get; set; }
        public int FEEDBACK_EMPLOYEE { get; set; }
        public Nullable<int> STAR_CONSIDER { get; set; }
        public string CONTENT { get; set; }
    
        public virtual PROFILE PROFILE { get; set; }
        public virtual PROFILE PROFILE1 { get; set; }
        public virtual JOB_RECUMENT JOB_RECUMENT { get; set; }
    }
}
