//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Website_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFILE()
        {
            this.FEED_BACKLIST = new HashSet<FEED_BACKLIST>();
            this.FEED_BACKLIST1 = new HashSet<FEED_BACKLIST>();
            this.JOB_RECUMENT = new HashSet<JOB_RECUMENT>();
            this.JOB_RECUMENT_PROCESSING = new HashSet<JOB_RECUMENT_PROCESSING>();
            this.JOB_WAGE_BILL = new HashSet<JOB_WAGE_BILL>();
            this.JOB_WAGE_BILL1 = new HashSet<JOB_WAGE_BILL>();
        }
    
        public int PROFILE_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string IDENTITY_CARD { get; set; }
        public string BIRTHDAY { get; set; }
        public string SEX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> PHONE { get; set; }
        public Nullable<int> TOWN_ID { get; set; }
        public string ADDRESS { get; set; }
        public string AVATAR { get; set; }
        public string DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEED_BACKLIST> FEED_BACKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEED_BACKLIST> FEED_BACKLIST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB_RECUMENT> JOB_RECUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB_RECUMENT_PROCESSING> JOB_RECUMENT_PROCESSING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB_WAGE_BILL> JOB_WAGE_BILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB_WAGE_BILL> JOB_WAGE_BILL1 { get; set; }
        public virtual TOWN TOWN { get; set; }
    }
}
