//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Website_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERRAL_WAGE_BILL
    {
        public int REFERRAL_ID { get; set; }
        public int RECUMENT_ID { get; set; }
        public Nullable<double> REFERRAL_WAGE_COST { get; set; }
        public string PAYMENT_DATE { get; set; }
        public string CARD_NUMBER { get; set; }
    
        public virtual JOB_RECUMENT JOB_RECUMENT { get; set; }
        public virtual USERPAYCARD USERPAYCARD { get; set; }
    }
}
