//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Website_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USER
    {
        //[Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int USER_ID { get; set; }
        [DisplayName("Tên tài khoản")]
        [Required(ErrorMessage = "Tài khoản không được bỏ trống")]
        public string USERNAME { get; set; }

        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được bỏ trống")]
        public string PASSWORD { get; set; }

        [DisplayName("Nhập lại mật khẩu")]
        [Required(ErrorMessage ="Mật khẩu nhập lại không được bỏ trống")]
        [Compare(nameof(PASSWORD),ErrorMessage ="Mật khẩu nhập lại không giống mật khẩu trước đó")]
        public string PASSWORDAGAIN { get; set; }

        [DisplayName("Trạng thái người dùng")]
        public Nullable<byte> USER_STATUS { get; set; }

        [DisplayName("Chức vụ")]
        [Required(ErrorMessage = "Chức vụ không được bỏ trống")]
        public Nullable<byte> ROLE_ID { get; set; }


        [DisplayName("Ngày tham gia")]
        public string JOINED_DATE { get; set; }
        [DisplayName("Facebook ID")]
        public string FACEBOOK_ID { get; set; }
        [DisplayName("Gmail ID")]
        public string GMAIL_ID { get; set; }
        [DisplayName("Reset Token")]
        public string RESET_TOKEN { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
